---

- name: Configure system environment
  hosts: workstations
  connection: local
  become: true
  tasks:

  - name: install packages and update cache
    package:
      name:
        - neovim
        - tmux
      state: latest
      update_cache: yes
