---

- name: Configure system environment
  hosts: workstations
  connection: local
  become: true
  tasks:

  - name: create frank user
    tags:
      - full-install
      - user-create
    user:
      name: frank
      groups: root

  - name: add ssh key for frank
    tags:
      - full-install
      - ssh-config
    authorized_key:
      user: frank
      key: ""

  - name: install packages and update cache
    tags:
      - packages
      - full-install
    package:
      name:
        - "{{ neovim }}"
        - "{{ tmux }}"
        - "{{ nvidia }}"
        - "{{ xorg-server }}"
        - "{{ xorg-xinit }}"
        - "{{ xorg-xsetroot }}"
        - "{{ xorg-xrandr }}"
        - "{{ nitrogen }}"
        - "{{ spotifyd }}"
        - "{{ xautolock }}"
        - "{{ git }}"
        - "{{ xbindkeys }}"
        - "{{ python-pip }}"
        - "{{ feh }}"
        - "{{ dbeaver }}"
        - "{{ unclutter }}"
        - "{{ bluez }}"
        - "{{ bluez-tools }}"
        - "{{ bluez-utils }}"
        - "{{ pulseaudio }}"
        - "{{ pulseaudio-bluetooth }}"
        - "{{ base-devel }}"
        - "{{ xclip }}"
        - "{{ ttf-nerd-fonts-symbols-mono }}"
        - "{{ brightnessctl }}"
        - "{{ alsa-utils }}"
        - "{{ pavucontrol }}"
        - "{{ lxappearance }}"
        - "{{ arc-gtk-theme }}"
        - "{{ doas }}"
        - "{{ connman }}"
        - "{{ wpa_supplicant }}"
        - "{{ pamixer }}"
        - "{{ ripgrep }}"
        - "{{ fd }}"
        - "{{ fzf }}"
        - "{{ jupyter }}"
        - "{{ baobab }}"
        - "{{ nethogs }}"
        - "{{ virt-manager }}"
        - "{{ qemu }}"
        - "{{ libvirt }}"
        - "{{ lxsession }}"
        - "{{ spice-vdagent }}"
        - "{{ flameshot }}"
        - "{{ clipmenu }}"
        - "{{ arandr }}"
        - "{{ numlockx }}"
        - "{{ broadcom-wl }}"
        - "{{ bat }}"
        - "{{ dunst }}"
      state: latest
      update_cache: yes

  - name: Cloning .dotfiles
    tags:
      - dotfiles
      - full-install
    ansible.builtin.git:
      repo: 'git@github.com:andre-gonzalez/dotfiles.git'
      dest: "{{ lookup('env', 'USR') | default('nobody', True) }}"
      recursive: yes
      update: yes
      bare: yes
      version: main

  - name: start services
    tags:
      - start-services
      - full-install
    service:
      name:
        - iwd
        - libvirt
      state: started
      enabled: yes

  - name: Git personal setup email
    tags:
      - git-personal
      - full-install
    community.general.git_config:
      name: user.email
      scope: global
      value: "lopescg@gmail.com"

  - name: Git personal setup name
    tags:
      - git-personal
      - full-install
    community.general.git_config:
      name: user.name
      scope: global
      value: "André Gonzalez"

  - name: Git eureciclo email
    tags:
      - git-eureciclo
      - full-install
    community.general.git_config:
      name: user.email
      scope: global
      value: "andre.gonzalez@nhecotech.com"

- name: Clone yay
  tags:
    - aur-install
    - full-install
  git:
    repo: https://aur.archlinux.org/yay-bin.git
    dest: "{{ lookup('env', 'USR') | default('nobody', True) }}/.config/yay"

    update: true

- name: Build and install yay
  tags:
    - aur-install
    - full-install
  git:
  command:
    chdir: "{{ lookup('env', 'USR') | default('nobody', True) }}/.config/yay"
    cmd: "makepkg -sfi --noconfirm"
    creates: /usr/bin/yay
