---

- name: Configure system environment
  hosts: workstations
  connection: local
  become: true
  tasks:

  - name: install packages and update cache
    tags: install-packages, arch
    package:
      name:
        - neovim
        - tmux
      state: latest
      update_cache: yes

  - name: Copy dotfiles
    tags: copy-dotfiles, arch, ubuntu, debian
    copy:
      src: ../dotfiles/
      dest: $HOME/

  - name: start services
    tags: start-services, arch, ubuntu, debian
    service:
      name:
      state: started
