---

- name: Configure system environment
  hosts: workstations
  connection: local
  become: true
  tasks:

  - name: install packages and update cache
    tags:
      - packages
      - install
    package:
      name:
        - neovim
        - tmux
      state: latest
      update_cache: yes
    when: ansible_distribution == "Archlinux"

  - name: Cloning .dotfiles
    tags:
      - dotfiles
      - install
    ansible.builtin.git:
      repo: 'git@github.com:andre-gonzalez/dotfiles.git'
      dest: /home/frank/
      recursive: yes
      update: yes
      version: main
    when: ansible_distribution == ["Archlinux", "Debian", "Ubuntu"]

  - name: start services
    tags:
      - start-services
      - install
    service:
      name:
      state: started
      enabled: yes
    when: ansible_distribution == ["Archlinux", "Debian", "Ubuntu"]

  - name: Git personal setup email
    tags:
      - git-personal
      - install
    git-config:
      name: user.email
      scope: global
      value: "lopescg@gmail.com"

  - name: Git personal setup name
    tags:
      - git-personal
      - install
    git-config:
      name: user.name
      scope: global
      value: "André Gonzalez"

  - name: Git eureciclo email
    tags:
      - git-eureciclo
      - install
    git-config:
      name: user.email
      scope: global
      value: "andre.gonzalez@nhecotech.com"
