---

- name: Install arch linux environment
  hosts: all
  connection: local
  become: true
  tasks:

  - name: install nvim
    community.general.pacman:
      name:
        - neovim
        - tmux
      state: latest
      update_cache: yes
    when: ansible_distribution == "Archlinux"

