---

- name: Install arch linux environment
  hosts: all
  connection: local
  become: true
  tasks:

  - name: install arch linux packages and update cache
    community.general.pacman:
      name:
        - neovim
        - tmux
      state: latest
      update_cache: yes
    when: ansible_distribution == "Archlinux"

  - name: install debian packages and update cache
    apt:
      name:
        - neovim
        - tmux
      state: latest
      update_cache: yes
    when: ansible_distribution == ["Debian" , "Ubuntu"]

